/***************************************************************************//**
* \file XIAODU_XIAODU_INT8_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains XIAODU_XIAODU_INT8 model data.
* Date: 2026-04-24 20:40:45.247926
*******************************************************************************
* \copyright
* Copyright 2026, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/

/*
ml-coretools 3.1.0.9423 based on TensorFlow 2.19.0 and ethos-u-vela 4.5.0
    ml-coretools-middleware-streaming 3.2.0.16332
    ml-coretools-tflm-qemu-images 3.2.0.16332
*/

#ifndef XIAODU_XIAODU_INT8_TFLM_MODEL_INT8X8_H
#define XIAODU_XIAODU_INT8_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t XIAODU_XIAODU_INT8_model_bin[];
#else
extern uint8_t XIAODU_XIAODU_INT8_model_bin[];
#endif // CY_ML_MODEL_MEM
#define XIAODU_XIAODU_INT8_MODEL_BIN_LEN (133920u)
#define XIAODU_XIAODU_INT8_ARENA_SIZE (16384u)

#endif // XIAODU_XIAODU_INT8_TFLM_MODEL_INT8X8_H

