/***************************************************************************//**
* \file HEY_GOOGLE_INT8_tflm_model_int8x8.h
*
* \brief
* Autogenerated with ml-coretools, this file contains HEY_GOOGLE_INT8 model data.
* Date: 2023-10-14 16:08:00.940051
*******************************************************************************
* \copyright
* Copyright 2023, Cypress Semiconductor Corporation (an Infineon company).
* All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
******************************************************************************/


#ifndef HEY_GOOGLE_INT8_TFLM_MODEL_INT8X8_H
#define HEY_GOOGLE_INT8_TFLM_MODEL_INT8X8_H

#include <stdint.h>


#ifdef CY_ML_MODEL_MEM
extern const uint8_t HEY_GOOGLE_INT8_model_bin[];
#else
extern uint8_t HEY_GOOGLE_INT8_model_bin[];
#endif // CY_ML_MODEL_MEM
#define HEY_GOOGLE_INT8_MODEL_BIN_LEN (133608u)
#define HEY_GOOGLE_INT8_ARENA_SIZE (5809u)

#endif // HEY_GOOGLE_INT8_TFLM_MODEL_INT8X8_H


