/******************************************************************************
 * File Name: cy_lpwwd_postwwd.h
 *
 * Description: Header file with APIs & Data structures for post wake word detection.
 *
 *******************************************************************************
 * (c) 2021, Infineon Technologies Company. All rights reserved.
 *******************************************************************************
 * This software, including source code, documentation and related materials
 * ("Software"), is owned by Infineon Technologies Company (Infineon) or one of its
 * subsidiaries and is protected by and subject to worldwide patent
 * protection (United States and foreign), United States copyright laws and
 * international treaty provisions. Therefore, you may use this Software only
 * as provided in the license agreement accompanying the software package from
 * which you obtained this Software ("EULA").
 *
 * If no EULA applies, Infineon hereby grants you a personal, non-exclusive,
 * non-transferable license to copy, modify, and compile the Software source
 * code solely for use in connection with Infineon's integrated circuit products.
 * Any reproduction, modification, translation, compilation, or representation
 * of this Software except as specified above is prohibited without the express
 * written permission of Infineon.
 *
 * Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Infineon
 * reserves the right to make changes to the Software without notice. Infineon
 * does not assume any liability arising out of the application or use of the
 * Software or any product or circuit described in the Software. Infineon does
 * not authorize its products for use in any products where a malfunction or
 * failure of the Infineon product may reasonably be expected to result in
 * significant property damage, injury or death ("High Risk Product"). By
 * including Infineon's product in a High Risk Product, the manufacturer of such
 * system or application assumes all risk of such use and in doing so agrees to
 * indemnify Infineon against all liability.
 *******************************************************************************/
#ifndef __CY_LPWWD_POSTWWD_H
#define __CY_LPWWD_POSTWWD_H

#include "cy_result.h"
#include "cy_lpwwd_common.h"
#include "cy_lpwwd.h"
/******************************************************
 *                      Typedefs
 ******************************************************/

typedef int16_t LPWWD_POSTWWD_IP_DATA_TYPE_T;

/******************************************************
 *                      Function Prototypes
 ******************************************************/
/**
 * Initialized pre wake-word components.
 *
 * @param[in] config_params  Configuration parameters needed for the post wake word components
 *
 * @return    CY_RSLT_SUCCESS on success; an error code on failure.
 */
cy_rslt_t cy_lpwwd_postwwd_init(
		cy_lpwwd_postwwd_config_params_t *config_params);

/**
 * Feed the audio data to input pre wake-word components.
 *
 * @param[in] output_score             Output score generated by ML library. tokens * sizeof(ML type)
 *
 * @param[out] wwd_status              Decision will be set to CY_LPWWD_WAKE_WORD_DETECTED if wake word is detected, else it will be
 *                                     set to CY_LPWWD_WAKE_WORD_NOT_DETECTED if wake word is not detected. Refer \ref cy_lpwwd_wwd_detect_status_t
 *                                     for more status.
 *
 * @return    CY_RSLT_SUCCESS on success; an error code on failure.
 */
cy_rslt_t cy_lpwwd_postwwd_process(int16_t *output_score,
    cy_lpwwd_wwd_detect_status_t *wwd_status);

/**
 * Reset post processing component
 *
 * @return    CY_RSLT_SUCCESS on success; an error code on failure.
 */
cy_rslt_t cy_lpwwd_postwwd_reset( );

/**
 * De-Initialize post wake-word components.
 *
 * @return    CY_RSLT_SUCCESS on success; an error code on failure.
 */
cy_rslt_t cy_lpwwd_postwwd_deinit( );

#endif /*__CY_LPWWD_POSTWWD_H */

/* [] END OF FILE */
